# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodTruck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTruck

  target 'FoodTruckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodTruckUITests' do
    # Pods for testing
  end

pod 'SwiftLint'

end
